#!/bin/sh

# Run psort with 1, 2, 4, 8, 16 and 32 processes and display the time 
# it took to run on a new line (in seconds) in each case.
# Command line arguments:
#	- the first argument is the path of the file that psort will be run on
#	- the remaining arguments will be ignored

if [ ! -f $1 ]; then
    echo $1: file does not exist
else
    i="1"
    while [ "$i" -ne "64" ]; do
    	psort -n `expr $i` -f $1 -o "temp.b"
	i=`expr $i \* 2` 
    done
fi

if [ -f temp.b ]; then
    rm "temp.b"
fi

